export const PROFILE_FIXTURE: Profile = {
	id: "profile-1",
	authId: "auth-1",
	email: "ana@example.com",
	firstName: "Ana",
	lastName: "García",
	secondLastName: null,
	fullName: "Ana García",
	initials: "AG",
	avatarUrl: null,
	phone: "5551234567",
	currency: "MXN",
	locale: "es-MX",
	timezone: "America/Mexico_City",
	onboardingCompleted: true,
	estimatedMonthlyIncome: null,
	createdAt: "2026-01-15T10:30:00.000Z",
	updatedAt: "2026-07-24T18:00:00.000Z",
};
